### PR TITLE
Version stabilization for 17. 6 release

### PR DESCRIPTION
**Pull request by ankitvarmait**
Version stabilization for 17. 6 release

### CODE REVIEW

**Review by AArnott — APPROVED** [review]
Looks good, provided you've tested with `dotnet pack -p:publicrelease=true` with this change applied. The PR build doesn't test this, but the CI build may break if issues that this `dotnet pack` command could also find are not fixed.

**Comment by RyanToth3** [comment]
This references an unstable version of Threading

**Comment by AArnott** [comment]
@ankitvarmait are you saying you can't repro the problem that @ryantoth3 saw? I see it as well:

```
C:\Program Files\dotnet\sdk\7.0.103\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(221,5): warning NU5104: A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "Microsoft.VisualStudio.Threading [17.6.29-alpha, )" or update the version field in the nuspec. [C:\Users\andarno\source\repos\vs-streamjsonrpc\src\StreamJsonRpc\StreamJsonRpc.csproj]
C:\Program Files\dotnet\sdk\7.0.103\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(221,5): warning NU5104: A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "Microsoft.VisualStudio.Threading.Analyzers [17.6.29-alpha, )" or update the version field in the nuspec. [C:\Users\andarno\source\repos\vs-streamjsonrpc\src\StreamJsonRpc\StreamJsonRpc.csproj]
C:\Program Files\dotnet\sdk\7.0.103\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(221,5): warning NU5104: A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "Microsoft.VisualStudio.Threading [17.6.29-alpha, )" or update the version field in the nuspec. [C:\Users\andarno\source\repos\vs-streamjsonrpc\src\StreamJsonRpc\StreamJsonRpc.csproj]
C:\Program Files\dotnet\sdk\7.0.103\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(221,5): warning NU5104: A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "Microsoft.VisualStudio.Threading.Analyzers [17.6.29-alpha, )" or update the version field in the nuspec. [C:\Users\andarno\source\repos\vs-streamjsonrpc\src\StreamJsonRpc\StreamJsonRpc.csproj]
    4 Warning(s)
    0 Error(s)
```

We need to stabilize vs-threading first, spin a real-signed build, and then we can update that reference here in this repo and merge it before or with this PR.

**Comment by javierdlg** [comment]
@ankitvarmait you should make sure the package that is being built doesn't have an alpha tag. The `pack` command requires a new git commit for it to pick up the changes. I saw no errors initially, but after running `dotnet nuget locals -c http-cache`, committing a new change, and running `dotnet pack -p:publicrelease=true` I was able to get the preview version warnings.

**Pull request merged**
